# Generated by Django 4.1.7 on 2023-02-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeName', models.CharField(max_length=200)),
                ('incomeDescription', models.CharField(default=None, max_length=500, null=True)),
                ('incomeAmount', models.PositiveIntegerField(verbose_name='amouont')),
                ('incomeDate', models.DateField()),
            ],
        ),
    ]
