# Generated by Django 4.1.7 on 2023-02-24 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='income',
            name='incomeAmount',
            field=models.FloatField(verbose_name='incomeamouont'),
        ),
        migrations.AlterField(
            model_name='income',
            name='incomeDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='incomeDescription',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='incomeSource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income', to='income.incomesource'),
        ),
    ]
